### ISSUE TITLE
Testing party bugs: Any user can modify any list

### ISSUE THREAD

**Issue by furrkai** [gcivil-nyu-org/S2022-Team-5-repo#145]
<img width="1095" alt="1650141631(1)" src="https://user-images.githubusercontent.com/83237232/163690736-3297322d-e114-4d5c-870b-96b5a353d093.png">

<img width="666" alt="1650141874(1)" src="https://user-images.githubusercontent.com/83237232/163690810-04d9e623-bcc6-4741-88b2-455451cc8772.png">

"https://houseme-app.herokuapp.com/property/1" This list is not published by user "test1", but if I modify the id in URL "https://houseme-app.herokuapp.com/property/editlisting/id", I can modify this list or any list. 
The edit page needs to verify the permission.

**Comment by binvant** [comment]
Duplicate issue
