### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by EashanKaushik** [gcivil-nyu-org/S2022-Team-5-repo#149]
1. When I sign in and use the back button I can still see the sign-in page... 

![image.png](https://images.zenhubusercontent.com/62048bbc2e86b28f2d1ba001/d4c3cedc-b4b2-452c-8962-adb17f053379)

2. Signing In with already existing username

![image.png](https://images.zenhubusercontent.com/62048bbc2e86b28f2d1ba001/11536759-45e8-4aca-b173-298de66a4183)

3. On creating a new listing page was able to upload various file formats. 

Simple UI issue- View button going out of bounds (just for your reference as you progress forward)

![image.png](https://images.zenhubusercontent.com/62048bbc2e86b28f2d1ba001/dcb971f1-e831-493b-90fc-7de7a986b375)

![image.png](https://images.zenhubusercontent.com/62048bbc2e86b28f2d1ba001/06ad6731-f68e-40dd-aab5-0f5f00e3b073)

**Comment by binvant** [comment]
1.) The errorpage isn't set up yet that's why you see that page. Two users cannot have the same username.
2.) We've written in the document that the UI isn't optimized yet....

**Comment by EashanKaushik** [comment]
Thanks for the update. About point 2. I just added it for your reference. I will change accordingly.
