### ISSUE TITLE
Testing Party Bug ( Password field visible)

### ISSUE THREAD

**Issue by manektamanna** [gcivil-nyu-org/S2022-Team-5-repo#150]
While signing up, when we enter the password field, the password is visible and not encrypted.

![Screenshot (404)](https://user-images.githubusercontent.com/85683392/163731342-cd461d9b-0d15-4693-817a-4958655d477e.png)

**Comment by binvant** [comment]
It should be visible when you're setting up a new account and entering the password for the first time, the repeat password field should not be visible. While logging in, the password should not be visible and it isn't in our case..
