### ISSUE TITLE
Testing Party Bug ( New Listing Functionality not working properly)

### ISSUE THREAD

**Issue by manektamanna** [gcivil-nyu-org/S2022-Team-5-repo#153]
While creating a new listing, the Borough field and Pin code field are not validated. When I try to create a new listing with these nonvalidated fields, the page gets submitted successfully but we cannot see the newly created listing on the listings page because the Borough is not as per expected. Maybe you should have a drop-down field for Borough which allows you to choose one of the 5 Boroughs.

![Screenshot (407)](https://user-images.githubusercontent.com/85683392/163732198-bf8d5b13-3eb2-4864-ba62-2550acf04b2b.png)

**Comment by binvant** [comment]
Thanks for your insight. We've already replaced that with a dropdown menu but haven't committed the code yet to heroku. We plan to do that before this sprint ends
