### ISSUE TITLE
Testing Party

### ISSUE THREAD

**Issue by srijanmalhotra2711** [gcivil-nyu-org/S2022-Team-5-repo#155]
1. I tried to edit the listing but failed as I received an error.

![Screen Shot 2022-04-17 at 20.44.22.png](https://images.zenhubusercontent.com/62052e0dcd174000595a4a54/8702b647-2333-473c-9152-268c1ccaec25)

2. No way to toggle out of the VR Tour.

**Comment by binvant** [comment]
1.) As stated in the document, you need to enter all the fields for the edit listing function to work as of now. You didn't fill the 'Furnished' field
2.) Press the back button on your browser. The VR tour is a third party service
