### ISSUE TITLE
Testing Party issue

### ISSUE THREAD

**Issue by pb2640** [gcivil-nyu-org/S2022-Team-5-repo#156]
On creating a new user using sign in the django debug page shows up rather than specifying which input field was erroneous. I have attached the image for the input provided and the image for the error below:
![image](https://user-images.githubusercontent.com/90818379/163740209-c8370bad-b940-4ef0-8e13-c7c6497024ce.png)
![image](https://user-images.githubusercontent.com/90818379/163740029-9a2f4b9d-458f-4002-abef-31b994313aec.png)

The UI on the listings can be corrected, the button is flowing out of the container on the [link](https://houseme-app.herokuapp.com/property/browselistings):
![image](https://user-images.githubusercontent.com/90818379/163740302-a5441c74-02f9-4e0f-9529-a16d3b20fb05.png)

**Comment by binvant** [comment]
1.) That error is because your phone number's length is >10. We are working on handling these errors better
2.) As stated in the document, we know about this and are currently working on it.
