### ISSUE TITLE
Testing party bug

### ISSUE THREAD

**Issue by Shardhakoul** [gcivil-nyu-org/S2022-Team-5-repo#157]
1)In register mobile numbers can be of any length(should be limited to 10 digits). Also the profile gets created even if the confirm password field does not match the password is incorrect.
![image](https://user-images.githubusercontent.com/85691194/163748006-987f9ed6-cb36-449d-8390-43e52625ae05.png)

2)No message displayed when incorrect login credentials entered.

3)Not able to edit my listing
![image](https://user-images.githubusercontent.com/85691194/163748378-09325e8c-99b0-4065-aafd-963d08ff18c4.png)
![image](https://user-images.githubusercontent.com/85691194/163748410-cdb7d584-f6ec-4889-9ed8-78d2e7a96322.png)
![image](https://user-images.githubusercontent.com/85691194/163748436-d955fa90-b6f4-46de-a7fa-15cb357486ed.png)

**Comment by binvant** [comment]
1.) Duplicate issue
2.) Duplicate Issue
3.) As stated in the document, you need to provide some data in all the fields for that form to work right now. Correct me if I'm wrong but I think you didn't enter all the fields and that let to the error

**Comment by Shardhakoul** [comment]
Yes got it works that way
