### ISSUE TITLE
Testing party

### ISSUE THREAD

**Issue by nevermoreno1** [gcivil-nyu-org/S2022-Team-5-repo#159]
When I clicked view into one of the housing option, I scrolled down and tried to comment, but it failed when I clicked the "Comment" button. Also there are two hyperlinks for email and phone, but when I clicked it, it just went up to the image, which I doubt it properly worked.
<img width="1112" alt="Screen Shot 2022-04-18 at 4 43 14 PM" src="https://user-images.githubusercontent.com/51802554/163875247-78cf33e8-f528-42c7-8659-a7efdfa0b3b5.png">

**Comment by binvant** [comment]
Please read the document. We have stated that this should not be tested
